/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2016-02-15 08:46:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class detail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/footer.jsp", Long.valueOf(1455498865000L));
    _jspx_dependants.put("/WEB-INF/views/menu.jsp", Long.valueOf(1455525977000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/video.css\">\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-1.11.3.min.js\"></script>\r\n");
      out.write("<script src=\"http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js\"></script>\r\n");
      out.write("<title>노트르담 드 파리</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body >\r\n");
      out.write("<div data-role=\"page\" id=\"pageone\">\r\n");
      out.write("   ");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("  <div data-role=\"panel\" id=\"myPanel\" width=\"100px\" style=\"margin: 0%;\"> \n");
      out.write("   \n");
      out.write("    <ul data-role=\"listview\" data-inset=\"true\" data-theme=\"a\" data-divider-theme=\"b\">\n");
      out.write("    \t<li data-role=\"list-divider\">공연실황</li>\n");
      out.write("\t\t\t<li><a href=\"gohome\">한글자막</a></li>\n");
      out.write("\t\t\t<li><a href=\"#\">한국어</a></li>\n");
      out.write("\t\t\t<li><a href=\"#\">외국어</a></li>\n");
      out.write("\t\t<li data-role=\"list-divider\">노래방책</li>\n");
      out.write("\t\t\t<li><a href=\"song_t\">태진</a></li>\n");
      out.write("\t\t\t<li><a href=\"song_k\">금영</a></li>\n");
      out.write("\t</ul>\n");
      out.write("  </div> \n");
      out.write("  \n");
      out.write("  \n");
      out.write("  \n");
      out.write("  \n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <div data-role=\"header\">\r\n");
      out.write("  <a href=\"#myPanel\" class=\"ui-btn ui-shadow ui-corner-all ui-icon-bars ui-btn-icon-notext\">Open Panel</a>\r\n");
      out.write("    <h1>공연 실황</h1>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div data-role=\"main\" class=\"ui-content\">\r\n");
      out.write("   <br />\r\n");
      out.write("\t<font class=\"detail_font_title\">노트르담 드 파리(노트르담의 꼽추)</font>\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<font class=\"detail_font_title_original\">Notre-Dame de Paris</font>\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<font class=\"detail_font_title_desc\">1998 | 프랑스 | 송 쓰루 | 불어 | 한글자막</font>\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<br />\r\n");
      out.write("\r\n");
      out.write("\t<p>1막</p>\r\n");
      out.write("\t<div class=\"youtubeWrap\">\r\n");
      out.write("\t\t<iframe src=\"//www.youtube.com/embed/fD39Mi2bMdE?showinfo=0\"\r\n");
      out.write("\t\t\tframeborder=\"0\" allowfullscreen class=\"video\"></iframe>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br />\r\n");
      out.write("\t\r\n");
      out.write("\t<p>2막</p>\r\n");
      out.write("\t<div class=\"youtubeWrap\">\r\n");
      out.write("\t\t<iframe src=\"//www.youtube.com/embed/_g32VaxwVrw?showinfo=0\"\r\n");
      out.write("\t\t\tframeborder=\"0\" allowfullscreen class=\"video\"></iframe>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<p>\r\n");
      out.write("\t<table width=\"100%\" cellpadding=\"8px\">\r\n");
      out.write("\t\t<th bgcolor=\"#eeeeee\" align=\"left\">작품 정보</th>\r\n");
      out.write("\t\t<tr class=\"border_bottom\">\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<font size=\"1\" color=\"gray\">원작</font><br/>\r\n");
      out.write("\t\t\t\t<b>빅토르 마리 위고 Victor-marie Hugo의 소설 파리의 노트르담(노트르담의 곱추)</b>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t<tr class=\"border_bottom\">\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<font size=\"1\" color=\"gray\">작곡</font><br/>\r\n");
      out.write("\t\t\t\t<b>리카르도 코치안테 Riccardo Cocciante</b>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr class=\"border_bottom\">\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<font size=\"1\" color=\"gray\">작사</font><br/>\r\n");
      out.write("\t\t\t\t<b>뤽 플라몽동 Luc Plamondon</b>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<font size=\"1\" color=\"gray\">각본</font><br/>\r\n");
      out.write("\t\t\t\t<b>뤽 플라몽동 Luc Plamondon</b>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t<table width=\"100%\" cellpadding=\"8px\">\r\n");
      out.write("\t\t<th bgcolor=\"#eeeeee\" align=\"left\">공연 정보</th>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<font size=\"1\" color=\"gray\">공연장</font><br/>\r\n");
      out.write("\t\t\t\t<b>Live At The Palais des Congrès</b>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<table width=\"100%\" cellpadding=\"8px\">\r\n");
      out.write("\t\t<th bgcolor=\"#eeeeee\" align=\"left\">배역 정보</th>\r\n");
      out.write("\t\t<tr class=\"border_bottom\">\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<font size=\"1\" color=\"gray\">에스메랄다</font><br/>\r\n");
      out.write("\t\t\t\t<b>엘렌 세가라 Helene Segara</b>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t<tr class=\"border_bottom\">\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<font size=\"1\" color=\"gray\">콰지모도</font><br/>\r\n");
      out.write("\t\t\t\t<b>가루 Garou</b>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t<tr class=\"border_bottom\">\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<font size=\"1\" color=\"gray\">프롤로</font><br/>\r\n");
      out.write("\t\t\t\t<b>다니엘 라부아 Daniel Lavoie</b>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t<tr class=\"border_bottom\">\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<font size=\"1\" color=\"gray\">페뷔스</font><br/>\r\n");
      out.write("\t\t\t\t<b>파트리크 피오리 Patrick Fiori</b>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t<tr class=\"border_bottom\">\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<font size=\"1\" color=\"gray\">플뢰르 드 리스</font><br/>\r\n");
      out.write("\t\t\t\t<b>쥘리 제나티 Julie Zenatti</b>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t<tr class=\"border_bottom\">\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<font size=\"1\" color=\"gray\">그랭구아르</font><br/>\r\n");
      out.write("\t\t\t\t<b>브루노 펠티에 Bruno Pelletier</b>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t\t<font size=\"1\" color=\"gray\">클로팽</font><br/>\r\n");
      out.write("\t\t\t\t<b>뤼크 메르빌 Luck Mervil</b>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<br />\r\n");
      out.write("\t\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<table width=\"100%\" cellpadding=\"5px\">\r\n");
      out.write("\t<th bgcolor=\"#eeeeee\" align=\"left\"><b>넘버(원제/국내명)</b></th>\r\n");
      out.write("\t<tr><td bgcolor=\"e0e0e0\">1막</td></tr>\r\n");
      out.write("\t<tr class=\"border_bottom\">\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<font size=\"1\" color=\"gray\">Ouverture</font><br/>\r\n");
      out.write("\t\t\t<b>서곡</b>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr >\r\n");
      out.write("\t<tr class=\"border_bottom\">\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<font size=\"1\" color=\"gray\">Le temps des cathedrales</font><br/>\r\n");
      out.write("\t\t\t<b>대성당들의 시대</b>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr class=\"border_bottom\">\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<font size=\"1\" color=\"gray\">Les sans-papiers</font><br/>\r\n");
      out.write("\t\t\t<b>거리의 방랑자들</b>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr class=\"border_bottom\">\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<font size=\"1\" color=\"gray\">Intervention de Frollo</font><br/>\r\n");
      out.write("\t\t\t<b>프롤로의 명령</b>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr class=\"border_bottom\">\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<font size=\"1\" color=\"gray\">Danse d'Esmeralda</font><br/>\r\n");
      out.write("\t\t\t<b>에스메랄다의 춤</b>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr class=\"border_bottom\">\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<font size=\"1\" color=\"gray\">Bohemienne</font><br/>\r\n");
      out.write("\t\t\t<b>보헤미안</b>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr class=\"border_bottom\">\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<font size=\"1\" color=\"gray\">Esmeralda tu sais</font><br/>\r\n");
      out.write("\t\t\t<b>에스메랄다 너도</b>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr class=\"border_bottom\">\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<font size=\"1\" color=\"gray\">Ces diamants-lа</font><br/>\r\n");
      out.write("\t\t\t<b>다이아몬드</b>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr class=\"border_bottom\">\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<font size=\"1\" color=\"gray\">La fete des fous</font><br/>\r\n");
      out.write("\t\t\t<b>미치광이들의 축제</b>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr class=\"border_bottom\">\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<font size=\"1\" color=\"gray\">La sorciere</font><br/>\r\n");
      out.write("\t\t\t<b>마녀</b>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr class=\"border_bottom\">\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<font size=\"1\" color=\"gray\">L'enfant trouve</font><br/>\r\n");
      out.write("\t\t\t<b>버려진 아이</b>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr class=\"border_bottom\">\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<font size=\"1\" color=\"gray\">Les portes de Paris</font><br/>\r\n");
      out.write("\t\t\t<b>파리의 문들</b>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr class=\"border_bottom\">\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<font size=\"1\" color=\"gray\">Tentative d'enlevement</font><br/>\r\n");
      out.write("\t\t\t<b>납치 시도</b>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr class=\"border_bottom\">\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<font size=\"1\" color=\"gray\">La cour des miracles</font><br/>\r\n");
      out.write("\t\t\t<b>기적의 궁전</b>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr class=\"border_bottom\">\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<font size=\"1\" color=\"gray\">Le mot Phoebus</font><br/>\r\n");
      out.write("\t\t\t<b>페뷔스란 이름</b>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr class=\"border_bottom\">\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<font size=\"1\" color=\"gray\">Beau comme le soleil</font><br/>\r\n");
      out.write("\t\t\t<b>태양처럼 눈부신</b>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr class=\"border_bottom\">\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<font size=\"1\" color=\"gray\">Dechire</font><br/>\r\n");
      out.write("\t\t\t<b>괴로워</b>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr class=\"border_bottom\">\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<font size=\"1\" color=\"gray\">Anarkia</font><br/>\r\n");
      out.write("\t\t\t<b>아나키아</b>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr class=\"border_bottom\">\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<font size=\"1\" color=\"gray\">A boire</font><br/>\r\n");
      out.write("\t\t\t<b>물을 주오</b>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr class=\"border_bottom\">\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<font size=\"1\" color=\"gray\">Belle</font><br/>\r\n");
      out.write("\t\t\t<b>아름답다</b>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr class=\"border_bottom\">\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<font size=\"1\" color=\"gray\">Ma maison c'est ta maison</font><br/>\r\n");
      out.write("\t\t\t<b>내 집은 그대의 집</b>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr class=\"border_bottom\">\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<font size=\"1\" color=\"gray\">Ave Maria paпen</font><br/>\r\n");
      out.write("\t\t\t<b>이방인의 아베 마리아</b>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr class=\"border_bottom\">\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<font size=\"1\" color=\"gray\">Je sens ma vie qui bascule</font><br/>\r\n");
      out.write("\t\t\t<b>내 마음을 볼 수 있다면</b>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr class=\"border_bottom\">\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<font size=\"1\" color=\"gray\">Tu vas me detruire</font><br/>\r\n");
      out.write("\t\t\t<b>파멸의 길로 나를</b>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr class=\"border_bottom\">\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<font size=\"1\" color=\"gray\">L'ombre</font><br/>\r\n");
      out.write("\t\t\t<b>그림자</b>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr class=\"border_bottom\">\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<font size=\"1\" color=\"gray\">Le val d'amour</font><br/>\r\n");
      out.write("\t\t\t<b>발다무르 카바레</b>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr class=\"border_bottom\">\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<font size=\"1\" color=\"gray\">La voulpte</font><br/>\r\n");
      out.write("\t\t\t<b>사랑의 기쁨</b>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr class=\"border_bottom\">\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<font size=\"1\" color=\"gray\">Fatalite</font><br/>\r\n");
      out.write("\t\t\t<b>숙명이여</b>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</table>\r\n");
      out.write("    \r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div data-role=\"footer\">\r\n");
      out.write("    ");
      out.write("\t\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<p align=\"center\"><font size=\"2\">Since 2016. © Mureka</font></p>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("  </div> \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
